[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

lib_deps =
  bodmer/TFT_eSPI@^2.5.0
  lvgl/lvgl@^8.3.11
  mikalhart/TinyGPSPlus@^1.1.0
  paulstoffregen/OneWire@^2.3.7
  milesburton/DallasTemperature@^3.11.0
  ricmoo/QRCode@^0.0.1
  h2zero/NimBLE-Arduino@^2.3.6

build_flags =
  -D LV_CONF_INCLUDE_SIMPLE
  -D USER_SETUP_LOADED=1
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D ST7735_DRIVER=1
  -D ST7735_BLACKTAB=1
  -D TFT_WIDTH=128
  -D TFT_HEIGHT=160
  -D TFT_MOSI=23
  -D TFT_SCLK=18
  -D TFT_CS=5
  -D TFT_DC=2
  -D TFT_RST=4
  ; если BLK (LED/BL) выведен на GPIO, укажи его:
  ; -D TFT_BL=25
  ; -D TFT_BACKLIGHT_ON=HIGH
  ; если всё еще есть смещение, попробуй:
  ; -D ST7735_REDTAB=1
  -D SPI_FREQUENCY=10000000

build_src_filter =
  -<*>
  +<main.cpp>
  +<printer_module.cpp>
  +<lv_font_ru_12.c>
  +<lv_font_ru_14.c>
